name: JS Tests
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install #if the file is present

      - name: Run Tests
        run: npm test
  
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repos
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Deploy application
        run: |
          echo "Deploying applicaton..."